import {test} from 'node:test';import assert from 'node:assert/strict';import {Survival,enemyStep,checkpoints,meltyCompatibility} from '../src/core.js';import {createPhysics} from '../src/physics.js';
test('entry requires proximity, exit requires stop',()=>{const s=new Survival();s.interact({x:10,z:0},{x:0,z:0},0);assert.equal(s.driving,false);s.interact({x:2,z:0},{x:0,z:0},0);assert.equal(s.driving,true);s.interact({x:0,z:0},{x:0,z:0},3);assert.equal(s.driving,true);s.interact({x:0,z:0},{x:0,z:0},0);assert.equal(s.driving,false);});
test('fuel exhaustion and damage disable engine',()=>{const s=new Survival();s.driving=true;s.fuel=.001;s.tick(1,1);assert.equal(s.fuel,0);assert.equal(s.engineAvailable,false);s.fuel=10;s.damage(150,true);assert.equal(s.integrity,0);assert.equal(s.engineAvailable,false);s.damage(-9,true);assert.equal(s.integrity,0);});
test('service location, stopped vehicle, finite resources',()=>{const s=new Survival();s.damage(50,true);s.service('repair',{x:40,z:0});assert.equal(s.integrity,50);s.service('repair',{x:0,z:8},0,{x:50,z:0});assert.equal(s.integrity,50);s.service('repair',{x:0,z:8},5);assert.equal(s.scrap,5);s.service('repair',{x:0,z:8});assert.equal(s.integrity,85);assert.equal(s.scrap,4);s.fuel=0;s.service('fuel',{x:0,z:8});assert.equal(s.fuel,15);assert.equal(s.canisters,2);});
test('hunger, food and death are bounded',()=>{const s=new Survival();s.hunger=.01;s.tick(1);assert.equal(s.hunger,0);assert.ok(s.health<100);assert.equal(s.eat(),true);assert.equal(s.food,2);s.damage(1000);s.tick(1000);assert.equal(s.health,0);assert.equal(s.eat(),false);assert.equal(s.startRace(),false);});
test('race has ordered checkpoints and no time limit',()=>{const s=new Survival();assert.equal(s.startRace(),false);s.driving=true;s.startRace();for(let i=0;i<10000;i++){s.tick(1);s.hunger=100;s.fuel=45;}assert.equal(s.race.active,true);assert.equal(s.updateRace(checkpoints[2]),false);for(const p of checkpoints)assert.equal(s.updateRace(p),true);assert.equal(s.race.completed,true);assert.equal(s.scrap,7);assert.equal(s.canisters,4);s.updateRace(checkpoints[5]);assert.equal(s.scrap,7);});
test('enemy pursuit, cooldown and vehicle targeting',()=>{const e={x:10,z:0,sight:20,speed:2,damage:8,cooldown:0};assert.equal(enemyStep(e,{x:0,z:0},1,false),null);assert.equal(e.x,8);e.x=2;assert.deepEqual(enemyStep(e,{x:0,z:0},.01,true),{amount:8,vehicle:true});assert.equal(enemyStep(e,{x:0,z:0},.1,true),null);});
test('Melty explicitly unavailable',()=>assert.equal(meltyCompatibility().available,false));
test('physical suspension settles and AWD accelerates then brakes',()=>{const p=createPhysics();for(let i=0;i<180;i++){p.controls(0,0,false,true);p.world.step(1/60);}assert.equal(p.vehicle.wheelInfos.length,4);assert.ok(p.vehicle.wheelInfos.every(w=>w.isInContact));assert.ok(p.chassis.position.y>.5&&p.chassis.position.y<1.2);for(let i=0;i<120;i++){p.controls(1,0,false,true);p.world.step(1/60);}const speed=p.chassis.velocity.length();assert.ok(speed>3);assert.ok(p.vehicle.wheelInfos.every(w=>w.engineForce===1300));for(let i=0;i<180;i++){p.controls(0,0,true,true);p.world.step(1/60);}assert.ok(p.chassis.velocity.length()<speed*.3);});
