"""Add our original C# files to an actual ModAPI-generated The Forest project.

Never fabricate DLLs, a loader, a game version or a Melty recipe.
"""
import argparse
from pathlib import Path
import shutil
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
NS = "http://schemas.microsoft.com/developer/msbuild/2003"
ET.register_namespace("", NS)


def prepare(project):
    project = Path(project).resolve()
    tree = ET.parse(project)
    root = tree.getroot()
    if root.tag != f"{{{NS}}}Project":
        raise ValueError("Expected a traditional ModAPI-generated C# project.")
    name = root.find(f".//{{{NS}}}AssemblyName")
    if name is None or name.text != "CannibalRallyExperimental":
        raise ValueError("Create project ID CannibalRallyExperimental in ModAPI first.")
    refs = root.findall(f".//{{{NS}}}Reference")
    names = {r.get("Include", "").split(",")[0] for r in refs}
    for required in ("BaseModLib", "UnityEngine", "Assembly-CSharp", "bolt"):
        if required not in names:
            raise ValueError(f"Generated project lacks required reference: {required}")
    for reference in refs:
        # Loader/game references must never be redistributed with our source build.
        private = reference.find(f"{{{NS}}}Private")
        if private is None:
            private = ET.SubElement(reference, f"{{{NS}}}Private")
        private.text = "False"
    backup = project.with_suffix(project.suffix + ".pre-rally.bak")
    if not backup.exists():
        shutil.copy2(project, backup)
    destination = project.parent / "CannibalRallySource"
    existing = {item.get("Include", "").replace("\\", "/") for item in root.findall(f".//{{{NS}}}Compile")}
    group = ET.SubElement(root, f"{{{NS}}}ItemGroup")
    for folder in ("Core", "Runtime"):
        for source in sorted((ROOT / "native" / folder).glob("*.cs")):
            target = destination / folder / source.name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            relative = target.relative_to(project.parent).as_posix()
            if relative not in existing:
                ET.SubElement(group, f"{{{NS}}}Compile", {"Include": relative})
    if not list(group):
        root.remove(group)
    tree.write(project, encoding="utf-8", xml_declaration=True)
    print("Prepared source only; build with the framework/references generated by your ModAPI.")
    print("No .mod or Melty ZIP was created. Original project backup:", backup)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path)
    args = parser.parse_args()
    prepare(args.project)
